name: Trigger auto deployment for containerappexample1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/containerappexample1-AutoDeployTrigger-f31f8a77-3977-4bb9-aab1-648841329030.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPEXAMPLE1_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPEXAMPLE1_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPEXAMPLE1_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPEXAMPLE1_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPEXAMPLE1_REGISTRY_PASSWORD }}
          containerAppName: containerappexample1
          resourceGroup: az104
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


